# Generated by Django 2.2.3 on 2022-03-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20220307_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
